spring:
  application:
    name: opendata-crud
  datasource:
    url: jdbc:mariadb://localhost:3306/boite
    username: root
    password: "0000"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

